CREATE DATABASE go2music;
CREATE USER 'go2music'@'localhost' IDENTIFIED BY 'go2music';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON go2music.* TO 'go2music'@'localhost';
