version: '2'

services:
  db:
    image: mysql:8.0
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go2music
      MYSQL_USER: go2music
      MYSQL_PASSWORD: go2music
    networks:
    - go2music_mysql_net
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

  go2music:
    depends_on:
    - db
    build: '.'
    ports:
    - "8080:8080"
    volumes:
    - go2music_data:/config
    - /mnt/audio:/music
    networks:
      - go2music_mysql_net
    restart: always
    environment:
      GO2MUSIC_DBTYPE: mysql
      GO2MUSIC_DBURL: go2music:go2music@tcp(db:3306)/go2music
      GO2MUSIC_DBSERVER: db:3306
      GO2MUSIC_DBSCHEMA: go2music
      GO2MUSIC_DBUSERNAME: go2music
      GO2MUSIC_DBPASSWORD: go2music
      GO2MUSIC_MEDIAPATH: /music
      GO2MUSIC_BULKINSERT: true

volumes:
  db_data: {}
  go2music_data: {}

networks:
  go2music_mysql_net:
    driver: bridge
