version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go2music
      MYSQL_USER: go2music
      MYSQL_PASSWORD: go2music
    networks:
    - go2music_mysql_net

  go2music:
    depends_on:
    - db
    image: go2music:1.3
    ports:
    - "8080:8080"
    volumes:
    - go2music_data:/config
    - /media/music:/music
    networks:
      - go2music_mysql_net
    restart: always
    environment:
      GO2MUSIC_DBTYPE: mysql
      GO2MUSIC_DBURL: go2music:go2music@tcp(db:3306)/go2music
      GO2MUSIC_DBSERVER: db:3306
      GO2MUSIC_DBSCHEMA: go2music
      GO2MUSIC_DBUSERNAME: go2music
      GO2MUSIC_DBPASSWORD: go2music
      GO2MUSIC_MEDIAPATH: /music

volumes:
  db_data: {}
  go2music_data: {}

networks:
  go2music_mysql_net:
    driver: bridge