swagger: "2.0"
info:
  title: "go2music API"
  description: "API description in Markdown."
  version: "1.0.0"
  contact:
    email: "info@b-4.de""
    name: "Michael Bernards"
host: "localhost:8080"
basePath: "/api"
schemes:
- "https"
- "http"
paths:
  /user:
    get:
      summary: "Returns a list of users."
      description: "Optional extended description in Markdown."
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
        401:
          description: "Not authorized"
