{
 "title": "Go2Music",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"go2music\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"go2music\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"go2music\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "http requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "http requests by methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method)(rate(http_total[$__rate_interval]))",
     "legendFormat": "{{methos}}"
    }
   ]
  },
  {
   "title": "http requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_total[$__rate_interval]))",
     "legendFormat": "http {{status}}"
    }
   ]
  },
  {
   "title": "http requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_total[$__rate_interval]))",
     "legendFormat": "go2music"
    }
   ]
  },
  { "title": "Static stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics{value=\"songs\"}",
     "legendFormat": "Songs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics{value=\"artists\"}",
     "legendFormat": "Artists"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics{value=\"albums\"}",
     "legendFormat": "Albums"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics{value=\"playlists\"}",
     "legendFormat": "Playlists"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics{value=\"users\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "statistics{value=\"totalLength\"}",
     "legendFormat": "Total length"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests per page",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (uri, Time) (http_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per method",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 23 },
   "targets": [
    { "expr": "sum by (method) (http_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per status",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 23 },
   "targets": [
    { "expr": "sum by (status) (http_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}