CREATE DATABASE go2music CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'go2music'@'%' IDENTIFIED BY 'go2music';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON go2music.* TO 'go2music'@'%';
