SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE user_song;
TRUNCATE TABLE playlist_song;
TRUNCATE TABLE playlist;
TRUNCATE TABLE song;
TRUNCATE TABLE album;
TRUNCATE TABLE artist;
SET FOREIGN_KEY_CHECKS = 1;
