name: Build pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Frontend
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          #cache: 'npm'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Install Angular/CLI
        run: npm install -g @angular/cli > /dev/null
        working-directory: ./frontend
      - name: Build frontend
        run: ng build --configuration production
        working-directory: ./frontend
      # Services
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Generate artifacts
        run: |
          go version
          go get golang.org/x/lint/golint
          go install golang.org/x/lint/golint
          go generate ./...
      - name: Build
        run: go build -v ./...
      - name: Lint
        run: |
          go vet .
          golint
      - name: Test
        #run: go test -v ./...
        run: echo "Tests should go here....."
